version: 0.1

phases:
  pre_build:
    commands:
      - aws cp s3://$S3_BUCKET/gdrive-lambda/zappa_settings.json .
      - aws cp s3://$S3_BUCKET/gdrive-lambda/settings-dev.yaml .
      - aws cp s3://$S3_BUCKET/gdrive-lambda/client_secrets-dev.p12 .
  build:
    commands:
      - |
        virtualenv venv && \
        source ./venv/bin/activate && \
        pip install -r requirements.txt && \
        zappa update dev
  post_build:
    commands:
      - rm zappa_settings.json
      - rm settings-dev.yaml
      - rm client_secrets-dev.p12
